---
all:
  children:
    linux:
      hosts:
        cs-ansible:
          ansible_user: root
          ansible_host: 10.111.255.20
        cs-ansible.granbury.k12.tx.us:
          ansible_user: root
          ansible_host: 10.111.255.20
        cs-centos:
          ansible_user: root
          ansible_host: 10.111.255.33
        adm-mailrelay:
          ansible_user: root
          ansible_host: 10.111.2.16
          ansible_python_interpreter: '/usr/bin/python3'
        tec-ntop:
          ansible_user: root
          ansible_host: 10.111.2.92
        myip:
          ansible_user: root
          ansible_host: 10.111.2.221
          ansible_python_interpreter: '/usr/bin/python'
        adm-ids-snort1:
          ansible_user: root
          ansible_host: 10.111.255.57
        tec-ids:
          ansible_user: root
          ansible_host: 10.111.255.202
        tec-dcim:
          ansible_user: root
          ansible_host: 10.111.255.160
        tec-hids:
          ansible_user: root
          ansible_host: 10.191.255.1
        tec-mailrelay:
          ansible_user: ansible
          ansible_host: 10.111.2.15
          ansible_pythone_interpreter: '/usr/bin/python'
        tec-syslog:
          ansible_user: root
          ansible_host: 10.111.49.90
        tec-syslog2:
          ansible_user: root
          ansible_host: 10.111.255.16
        graylog:
          ansible_user: root
          ansible_host: 10.111.255.10
          #ansible_python_interpreter: '/usr/bin/python3'
        tec-cs-centos-2:
          ansible_user: ansible
          ansible_host: 10.111.255.30

        #
        # NOC Cabinet C1
        #
        adm.noc.c1.ru26.x440g2.sw:
          ansible_host: 10.1.253.238
          ansible_connection: network_cli
          ansible_network_os: 'exos'
        adm.noc.c1.ru33.x670g2:
          ansible_host: 10.1.253.20
          ansible_connection: network_cli
          ansible_network_os: 'exos'

        #
        # NOC Cabinet C9
        #
        adm.noc.c9.r47.E440g2:
          ansible_host: 10.1.254.193
          ansible_connection: network_cli
          ansible_network_os: 'exos'

        #
        # NOC Cabinet C16
        #
        adm.noc.c16.x670.g2.ru42.sw:
         ansible_host: 10.1.253.244
         ansible_connection: network_cli
         ansible_network_os: 'exos'

        # 
        # ADM IDF1
        #
        adm-idf1-670g2-02:
          ansible_host: 10.1.253.237
          ansible_connection: network_cli
          ansible_network_os: 'exos'
        adm-idf1-440g2-03:
          ansible_host: 10.1.253.231
          ansible_connection: network_cli
          ansible_network_os: 'exos'
        adm-idf1-440g2-04:
          ansible_host: 10.1.253.235
          ansible_connection: network_cli
          ansible_network_os: 'exos'
        adm-idf1-440g2-05:
          ansible_host: 10.1.253.234
          ansible_connection: network_cli
          ansible_network_os: 'exos'
        adm-idf1-440g2-11:
          ansible_host: 10.1.253.240
          ansible_connection: network_cli
          ansible_network_os: 'exos'


       # 
       # ADM IDF2
       #
        adm-idf2-670g2-01:
          ansible_host: 10.1.253.228
          ansible_connection: network_cli
          ansible_network_os: 'exos'
        adm-idf2-440g2-01:
          ansible_host: 10.1.253.229
          ansible_connection: network_cli
          ansible_network_os: 'exos'
        adm-idf2-440g2-02:
          ansible_host: 10.1.253.230
          ansible_connection: network_cli
          ansible_network_os: 'exos'
        adm-idf2-440g2-03:
          ansible_host: 10.1.253.236
          ansible_connection: network_cli
          ansible_network_os: 'exos'
        adm-idf2-440g2-04:
          ansible_host: 10.1.253.232
          ansible_connection: network_cli
          ansible_network_os: 'exos'

      vars:
        ntp_server: time-a-b.nist.gov pool.ntp.org 0.pool.ntp.org 1.pool.ntp.org

    centos:
      hosts:
        cs-centos:
        adm-mailrelay:
        adm-ids-snort1:
        tec-cs-centos-2:
        tec-ids:
        tec-hids:
        tec-syslog:
        tec-syslog2:
        tec-mailrelay:
        tec-mailscan:
        myip:
        cs-ansible:
        tec-dcim:
        tec-observium:
        graylog:        
      vars:
        git_package: git

    centos8:
      hosts:
        cs-centos:
        adm-mailrelay:
      vars:
        git_package: git
        email_server_package: postfix

    ids:
      hosts:
        adm-ids-snort1:
        tec-ids:
        tec-hids:

    security:
      hosts:
        adm-ids-snort1:
        tec-ids:
        tec-hids:

    syslog:
      hosts:
        tec-syslog:
        tec-syslog2:

    mail:
      hosts:
        tec-mailrelay:
        tec-mailscan:
        adm-mailrelay:

    apache:
      hosts:
        myip:
          ansible_python_interpreter: '/usr/bin/python'
      vars:
        apache_package: httpd


    www:
      hosts:
        myip:
      vars:
        apache_package: httpd

    app:
      hosts:
        cs-ansible:
        cs-centos:
        tec-ntop:
        tec-dcim:
        tec-observium:
        graylog:

    noc_switches:
     hosts:
        adm.noc.c1.ru33.x670g2:
        adm.noc.c9.r47.E440g2:
        adm.noc.c1.ru26.x440g2.sw:
        # adm.noc.c16.x670.g2.ru42.sw:
    
    switches:
      hosts:
        adm.noc.c1.ru33.x670g2:
        adm.noc.c1.ru26.x440g2.sw:
        adm.noc.c9.r47.E440g2:
        adm.noc.c16.x670.g2.ru42.sw:
        adm-idf1-670g2-02:
        adm-idf1-440g2-03:
        adm-idf1-440g2-04:
        adm-idf1-440g2-05:
        adm-idf1-440g2-11:
        adm-idf2-670g2-01:
        adm-idf2-440g2-01:
        adm-idf2-440g2-02:
        adm-idf2-440g2-03:
        adm-idf2-440g2-04:

    extreme_x670_switches:
      hosts:
        adm.noc.c1.ru33.x670g2:
        adm.noc.c16.x670.g2.ru42.sw:
        adm-idf1-670g2-02:
        adm-idf2-670g2-01:

    extreme_x440_switches:
      hosts:
        adm.noc.c1.ru26.x440g2.sw:
        adm.noc.c9.r47.E440g2:
        adm-idf1-440g2-03:
        adm-idf1-440g2-04:
        adm-idf1-440g2-05:
        adm-idf1-440g2-11:
        adm-idf2-440g2-01:
        adm-idf2-440g2-02:
        adm-idf2-440g2-03:
        adm-idf2-440g2-04:
    
    adm_idf1:
      hosts:
        adm-idf1-670g2-02:
        adm-idf1-440g2-03:
        adm-idf1-440g2-04:
        adm-idf1-440g2-05:
        adm-idf1-440g2-11:

    adm_idf2:
      hosts:
        adm-idf2-670g2-01:
        adm-idf2-440g2-01:
        adm-idf2-440g2-02:
        adm-idf2-440g2-03:
        adm-idf2-440g2-04:
